stages:
- stage: ContractTests
  displayName: 'Contract Tests (Pact)'
  dependsOn: UnitTests
  jobs:
  - job: ContractTests
    displayName: 'Run Contract Tests'
    pool:
      vmImage: 'windows-latest'
    variables:
      # Configure these in pipeline variables (mark secrets as secret)
      # Or use a variable group
      PACT_BROKER_BASE_URL: 'https://pact-broker.orangeisland-078e5d22.centralus.azurecontainerapps.io'
      PACT_BROKER_USERNAME: 'admin'
      PACT_BROKER_PASSWORD: 'admin123!'
      PROVIDER_VERSION: $(Build.BuildId)
      PUBLISH_VERIFICATION_RESULTS: 'true'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'
      displayName: 'Setup .NET 8 SDK'

    - script: dotnet restore
      displayName: 'Restore Dependencies'

    # Consumer Tests (generate pacts)
    - script: dotnet test tests/OrderService.Contract.Tests/OrderService.Contract.Tests.csproj --filter "OrderClientTests" --configuration Release --logger trx --results-directory $(Build.ArtifactStagingDirectory)/TestResults
      displayName: 'OrderService Consumer Tests'

    - script: dotnet test tests/InventoryService.Contract.Tests/InventoryService.Contract.Tests.csproj --filter "InventoryClientTests" --configuration Release --logger trx --results-directory $(Build.ArtifactStagingDirectory)/TestResults
      displayName: 'InventoryService Consumer Tests'

    # Publish pacts to broker
    - pwsh: |
        .\publish-pacts.ps1 -Version "$(Build.BuildId)" -Branch "$(Build.SourceBranchName)" -BrokerUrl "$(PACT_BROKER_BASE_URL)"
      displayName: 'Publish Pacts to Broker'
      env:
        PACT_BROKER_USERNAME: $(PACT_BROKER_USERNAME)
        PACT_BROKER_PASSWORD: $(PACT_BROKER_PASSWORD)

    # Verify pacts were published
    - pwsh: |
        Write-Host "Verifying pacts were published to broker..."
        $auth = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("$(PACT_BROKER_USERNAME):$(PACT_BROKER_PASSWORD)"))
        $headers = @{ "Authorization" = "Basic $auth"; "Accept" = "application/hal+json" }
        
        try {
            $response = Invoke-RestMethod -Uri "$(PACT_BROKER_BASE_URL)/pacts/provider/OrderServiceApi/latest" -Headers $headers -Method Get
            Write-Host "[OK] Found pacts for OrderServiceApi"
            Write-Host "Consumer: $($response._links.consumer.name)"
        } catch {
            Write-Host "[WARNING] No pacts found for OrderServiceApi yet"
            Write-Host "This may be expected on first run. Provider verification will be skipped."
        }
        
        try {
            $response = Invoke-RestMethod -Uri "$(PACT_BROKER_BASE_URL)/pacts/provider/InventoryService/latest" -Headers $headers -Method Get
            Write-Host "[OK] Found pacts for InventoryService"
            Write-Host "Consumer: $($response._links.consumer.name)"
        } catch {
            Write-Host "[WARNING] No pacts found for InventoryService yet"
        }
      displayName: 'Verify Pacts Published'
      continueOnError: true

    # Provider Verification Tests
    # Note: These may fail on first run if no pacts have been published yet
    - script: dotnet test tests/OrderService.Contract.Tests/OrderService.Contract.Tests.csproj --filter "OrderApiProviderTests" --configuration Release --logger trx --results-directory $(Build.ArtifactStagingDirectory)/TestResults
      displayName: 'OrderService Provider Verification'
      continueOnError: true  # Don't fail pipeline if no pacts exist yet
      env:
        PACT_BROKER_BASE_URL: $(PACT_BROKER_BASE_URL)
        PACT_BROKER_USERNAME: $(PACT_BROKER_USERNAME)
        PACT_BROKER_PASSWORD: $(PACT_BROKER_PASSWORD)
        PROVIDER_VERSION: $(Build.BuildId)
        PUBLISH_VERIFICATION_RESULTS: 'true'

    - script: dotnet test tests/InventoryService.Contract.Tests/InventoryService.Contract.Tests.csproj --filter "InventoryApiProviderTests" --configuration Release --logger trx --results-directory $(Build.ArtifactStagingDirectory)/TestResults
      displayName: 'InventoryService Provider Verification'
      continueOnError: true  # Don't fail pipeline if no pacts exist yet
      env:
        PACT_BROKER_BASE_URL: $(PACT_BROKER_BASE_URL)
        PACT_BROKER_USERNAME: $(PACT_BROKER_USERNAME)
        PACT_BROKER_PASSWORD: $(PACT_BROKER_PASSWORD)
        PROVIDER_VERSION: $(Build.BuildId)
        PUBLISH_VERIFICATION_RESULTS: 'true'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '$(Build.ArtifactStagingDirectory)/TestResults/*.trx'
        testRunTitle: 'Contract Tests'
      condition: always()
